Public Module Language

    Public NAMEString As String = "Name"
    Public SUBJECTString As String = "Subject"
    Public EMAILString As String = "Email"
    Public COMMENTString As String = "Comment"
    Public PASSWORDString As String = "Password"
    Public newthreadStr As String = "New thread"
    Public filesStr As String = "Files(s)"
    Public replyStr As String = "Reply"
    Public deleteStr As String = "Delete"
    Public reportStr As String = "Report"
    Public fileOnly As String = "File only"
    Public eachfileInNewpost As String = "Add each file to a seperate post"
    Public AnonName As String = "Anonymous"
    Public stickyStr As String = "Sticky"
    Public lockedStr As String = "Locked"
    Public prevStr As String = "Previous"
    Public nextStr As String = "Next"
    Public forPD As String = "For post deletion."
    Public postingModstr As String = "Posting mode: Reply "
    Public returnStr As String = "Return"
    Public addAnotherF As String = "Add another file"
    Public countFiles As String = "Count files"
    Public p1str As String = " % post(s) "
    Public andStr As String = " and "
    Public p2str As String = " % image reply(ies) "
    Public omittedStr As String = " omitted. Click <a href='%POSTLINK%' target='_blank' class='replylink'>here</a> to view."

    Public ImageRequired As String = "You cannot start a new thread without an image."
    Public SuccessfulPostString As String = "Post Succesful !"
    Public FileToBig As String = "The provided file is larger than the allowed limit (" & CStr(MaximumFileSize / 1024 / 1024) & " MB)"
    Public FloodDetected As String = "Flood detected, please allow " & TimeBetweenRequestes & " seconds before posting, reporting and deleting."
    Public CannotDeletePostBadPassword As String = "Cannot delete post % , bad password"
    Public PostDeletedSuccess As String = "Post number % has been deleted"
    Public NoPostWasSelected As String = "No post was selected"
    Public ReportedSucess As String = "Reported post number %"
    Public BadOrNoImage As String = "No image or image contains errors."
    Public BannedMessage As String = "You are banned from posting."
    Public lockedMessage As String = "Thread is locked."
    Public noBlankpost As String = "Blank post are not allowed"

#Region "Arabic"
    'Public NAMEString As String = "الاسم"
    'Public SUBJECTString As String = "الموضوع"
    'Public EMAILString As String = "البريد الاكتروني"
    'Public COMMENTString As String = "التعليق"
    'Public PASSWORDString As String = "كلمة السر"
    'Public newthreadStr As String = "موضوع جديد"
    'Public filesStr As String = "الملف(الملفات)"
    'Public replyStr As String = "رد"

    'Public ImageRequired As String = "لا يمكنك انشاء موضوع جديد من دون صورة"
    'Public SuccessfulPostString As String = "تم النشر بنجاح"
    'Public AnonName As String = "مجهول"
    'Public FileToBig As String = "الملغ المرفق يتجاوز الحد الأقصى المسموح به (" & CStr(MaximumFileSize / 1024 / 1024) & " ميجابايت)"

    'Public FloodDetected As String = "فائض من الطلبات, يرجي الانتظار  " & TimeBetweenRequestes & " ثوان قبل النشر و الحذف و التبليغ"

    'Public CannotDeletePostBadPassword As String = "لا يمكن حذف المنشور رقم % , كلمة السر غير صحيحة"
    'Public PostDeletedSuccess As String = "تم حذف المنشور رقم %"
    'Public NoPostWasSelected As String = "لم يتم اختيار أي منشور"

    'Public ReportedSucess As String = "تم التبليغ عن المنشور رقم %"
    'Public BadOrNoImage As String = "لا يوجد صورة أو الصورة تحتوي على أخطاء"
    'Public BannedMessage As String = "أنت ممنوع من القيام بالنشر"
    'Public stickyStr As String = "معلق"
    'Public lockedStr As String = "مقفول"
    'Public lockedMessage As String = "الموضوع مقفول"

    'Public noBlankpost As String = "المنشورات الفارغة ممنوعة"

    'Public p1str As String = "% منشور"
    'Public andStr As String = " و "
    'Public p2str As String = " % منشور مع صورة "
#End Region

#Region "French"
    'Public NAMEString As String = "Nom"
    'Public SUBJECTString As String = "Sujet"
    'Public EMAILString As String = "Email"
    'Public COMMENTString As String = "commentaire"
    'Public PASSWORDString As String = "Mot de passe"
    'Public newthreadStr As String = "Nouveau sujet"
    'Public replyStr As String = "Repondre"
    'Public filesStr As String = "Fichier(s)"
    'Public ImageRequired As String = "Vous ne pouvez pas commencer un nouvau sujet sans une image."
    'Public SuccessfulPostString As String = "La publication a été réussit!"
    'Public AnonName As String = "Anonyme"
    'Public FileToBig As String = "Le fichier fourni est supérieur à la limite autorisée (" & CStr(MaximumFileSize / 1024 / 1024) & " MO)"

    'Public FloodDetected As String = "Flood détecté, s'il vous plaît attendez " & TimeBetweenRequestes & " secondes avant de poster, de rapporter et de supprimer une pulication."
    '' 10 

    'Public CannotDeletePostBadPassword As String = "Impossible de supprimer la pulication %, mauvais mot de passe."
    'Public PostDeletedSuccess As String = "La pulication % a été supprimé"
    'Public NoPostWasSelected As String = "Aucun post a été selectionner."

    'Public ReportedSucess As String = "La pulication numéro % a été rapporter"
    'Public BadOrNoImage As String = "Aucune image fourni ou image contient des erreurs."
    'Public BannedMessage As String = "Vous êtes interdit de publier."
    'Public stickyStr As String = "épineux"
    'Public lockedStr As String = "Fermé"
    'Public lockedMessage As String = "Le sujet est fermé"

    'Public noBlankpost As String = "Les publication vides sont interdites."

    'Public p1str As String = " % publication(s) "
    'Public andStr As String = " et "
    'Public p2str As String = " % reponse(s) d'image "
#End Region

End Module
