Public Module Language

    Public ReadOnly NAMEString As String = "Name"
    Public ReadOnly SUBJECTString As String = "Subject"
    Public ReadOnly EMAILString As String = "Email"
    Public ReadOnly COMMENTString As String = "Comment"
    Public ReadOnly PASSWORDString As String = "Password"
    Public ReadOnly EnterCaptchastr As String = "Verification"
    Public ReadOnly newthreadStr As String = "New thread"
    Public ReadOnly filesStr As String = "Files(s)"
    Public ReadOnly replyStr As String = "Reply"
    Public ReadOnly deleteStr As String = "Delete"
    Public ReadOnly reportStr As String = "Report"
    Public ReadOnly fileOnly As String = "File only"
    Public ReadOnly eachfileInNewpost As String = "Add each file to a seperate post"
    Public ReadOnly AnonName As String = "Anonymous"
    Public ReadOnly stickyStr As String = "Sticky"
    Public ReadOnly lockedStr As String = "Locked"
    Public ReadOnly prevStr As String = "Previous"
    Public ReadOnly nextStr As String = "Next"
    Public ReadOnly forPD As String = "For post deletion."
    Public ReadOnly postingModstr As String = "Posting mode: Reply "
    Public ReadOnly returnStr As String = "Return"
    Public ReadOnly addAnotherF As String = "Add another file"
    Public ReadOnly countFiles As String = "Count files"
    Public ReadOnly p1str As String = " % post(s) "
    Public ReadOnly andStr As String = " and "
    Public ReadOnly p2str As String = " % image reply(ies) "
    Public ReadOnly omittedStr As String = " omitted. Click <a href='%POSTLINK%' target='_blank' class='replylink'>here</a> to view."
    Public ReadOnly banStr As String = "Ban user"
    Public ReadOnly deletepostStr As String = "Delete post"
    Public ReadOnly tgstickstr As String = "Toggle sticky"
    Public ReadOnly tglockstr As String = "Toggle Lock"
    Public ReadOnly editpostStr As String = "Edit post"
    Public ReadOnly posterIdstr As String = "Poster ID"
    Public ReadOnly topsrt As String = "Top"
    Public ReadOnly catalogstr As String = "Catalog"
    Public ReadOnly refreshStr As String = "Refresh"
    Public ReadOnly bottomstr As String = "Bottom"
    Public ReadOnly captchaChallengeStr As String = "Captcha Challenge"
    Public ReadOnly archiveStr As String = "Archive"

    Public ReadOnly ImageRequired As String = "You cannot start a new thread without an image."
    Public ReadOnly SuccessfulPostString As String = "Post Succesful !"
    Public ReadOnly FileToBig As String = "The provided file is larger than the allowed limit (" & CStr(MaximumFileSize / 1024 / 1024) & " MB)"
    Public ReadOnly FloodDetected As String = "Flood detected, please allow % seconds before posting, reporting and deleting."
    Public ReadOnly CannotDeletePostBadPassword As String = "Cannot delete post % , bad password"
    Public ReadOnly PostDeletedSuccess As String = "Post number % has been deleted"
    Public ReadOnly NoPostWasSelected As String = "No post was selected"
    Public ReadOnly ReportedSucess As String = "Reported post number %"
    Public ReadOnly BadOrNoImage As String = "No image or image contains errors."
    Public ReadOnly BannedMessage As String = "You are banned from posting."
    Public ReadOnly lockedMessage As String = "Thread is locked."
    Public ReadOnly noBlankpost As String = "Blank post are not allowed."
    Public ReadOnly duplicateFile As String = "Duplicate image detected."
    Public ReadOnly UnsupportedFile As String = "Unsupported file type."
    Public ReadOnly arhivedMessage As String = "This thread has 404'ed and it is in the archive now."
    Public ReadOnly invalidPostmodestr As String = "Invalid Posting mode"
    Public ReadOnly wrongCaptcha As String = "You have mistyped the captcha. Please try again."
    Public ReadOnly archiveNoticeStr As String = "This is the archive. Click <a href='" & WebRoot & "default.aspx'>here</a> to go back to the main page."

    Public ReadOnly banMsgStr As String = "User was banned for this post."
    Public ReadOnly commentToolong As String = "<br/><span class='summary'>Comment is too long. Click <a href='%POSTLINK%' target='_blank'>here</a> to view</span>"

#Region "Arabic"
    'Public NAMEString As String = "الاسم"
    'Public SUBJECTString As String = "الموضوع"
    'Public EMAILString As String = "البريد الاكتروني"
    'Public COMMENTString As String = "التعليق"
    'Public PASSWORDString As String = "كلمة السر"
    'Public newthreadStr As String = "موضوع جديد"
    'Public filesStr As String = "الملف(الملفات)"
    'Public replyStr As String = "رد"

    'Public ImageRequired As String = "لا يمكنك انشاء موضوع جديد من دون صورة"
    'Public SuccessfulPostString As String = "تم النشر بنجاح"
    'Public AnonName As String = "مجهول"
    'Public FileToBig As String = "الملغ المرفق يتجاوز الحد الأقصى المسموح به (" & CStr(MaximumFileSize / 1024 / 1024) & " ميجابايت)"

    'Public FloodDetected As String = "فائض من الطلبات, يرجي الانتظار  " & TimeBetweenRequestes & " ثوان قبل النشر و الحذف و التبليغ"

    'Public CannotDeletePostBadPassword As String = "لا يمكن حذف المنشور رقم % , كلمة السر غير صحيحة"
    'Public PostDeletedSuccess As String = "تم حذف المنشور رقم %"
    'Public NoPostWasSelected As String = "لم يتم اختيار أي منشور"

    'Public ReportedSucess As String = "تم التبليغ عن المنشور رقم %"
    'Public BadOrNoImage As String = "لا يوجد صورة أو الصورة تحتوي على أخطاء"
    'Public BannedMessage As String = "أنت ممنوع من القيام بالنشر"
    'Public stickyStr As String = "معلق"
    'Public lockedStr As String = "مقفول"
    'Public lockedMessage As String = "الموضوع مقفول"

    'Public noBlankpost As String = "المنشورات الفارغة ممنوعة"

    'Public p1str As String = "% منشور"
    'Public andStr As String = " و "
    'Public p2str As String = " % منشور مع صورة "
#End Region

#Region "French"
    'Public NAMEString As String = "Nom"
    'Public SUBJECTString As String = "Sujet"
    'Public EMAILString As String = "Email"
    'Public COMMENTString As String = "commentaire"
    'Public PASSWORDString As String = "Mot de passe"
    'Public newthreadStr As String = "Nouveau sujet"
    'Public replyStr As String = "Repondre"
    'Public filesStr As String = "Fichier(s)"
    'Public ImageRequired As String = "Vous ne pouvez pas commencer un nouvau sujet sans une image."
    'Public SuccessfulPostString As String = "La publication a été réussit!"
    'Public AnonName As String = "Anonyme"
    'Public FileToBig As String = "Le fichier fourni est supérieur à la limite autorisée (" & CStr(MaximumFileSize / 1024 / 1024) & " MO)"

    'Public FloodDetected As String = "Flood détecté, s'il vous plaît attendez " & TimeBetweenRequestes & " secondes avant de poster, de rapporter et de supprimer une pulication."
    '' 10 

    'Public CannotDeletePostBadPassword As String = "Impossible de supprimer la pulication %, mauvais mot de passe."
    'Public PostDeletedSuccess As String = "La pulication % a été supprimé"
    'Public NoPostWasSelected As String = "Aucun post a été selectionner."

    'Public ReportedSucess As String = "La pulication numéro % a été rapporter"
    'Public BadOrNoImage As String = "Aucune image fourni ou image contient des erreurs."
    'Public BannedMessage As String = "Vous êtes interdit de publier."
    'Public stickyStr As String = "épineux"
    'Public lockedStr As String = "Fermé"
    'Public lockedMessage As String = "Le sujet est fermé"

    'Public noBlankpost As String = "Les publication vides sont interdites."

    'Public p1str As String = " % publication(s) "
    'Public andStr As String = " et "
    'Public p2str As String = " % reponse(s) d'image "
#End Region

End Module
