'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("chanb.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /****** Object:  Table [dbo].[bans]    Script Date: 07/20/2013 08:13:55 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[bans]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[bans]
        '''
        '''/****** Object:  Table [dbo].[board]    Script Date: 07/20/2013 08:13:55 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[board]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[board]
        '''
        '''/****** Object:  Table [dbo].[files]    Script Date: 07/20/2013 08:13:55 ******/
        '''IF  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property mssqlDatabaseSetup() As String
            Get
                Return ResourceManager.GetString("mssqlDatabaseSetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- phpMyAdmin SQL Dump
        '''-- version 3.3.8.1
        '''-- http://www.phpmyadmin.net
        '''--
        '''-- Host: 127.0.0.1
        '''-- Generation Time: Jul 20, 2013 at 08:32 AM
        '''-- Server version: 5.1.51
        '''-- PHP Version: 5.3.3
        '''
        '''SET SQL_MODE=&quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        '''
        '''
        '''/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        '''/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        '''/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        '''/*!40101 SET NAMES utf8 */;
        '''
        '''--
        '''-- Database: `channelboard`
        '''--
        '''
        '''-- ------------------ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property mysqlDatabaseSetup() As String
            Get
                Return ResourceManager.GetString("mysqlDatabaseSetup", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
